### ISSUE TITLE
Add Aerys and ReactPHP to benchmarks

### ISSUE THREAD

**Issue by marcioAlmada** [kraken-php/framework#61]
The official website benchmarks many frameworks except the PHP ones that have a similar event-loop architecture. IMMO, It would be way more informative if Aerys and ReactPHP were featured too just for the sake of having a more oranges to oranges comparison.

PS: Just to be clear. I've tried kraken. It does what it promises and it's cool and I'm **not** implying the benchmarks are skewed in any way :)

**Comment by Arabic4222** [comment]
I've been having apache in my phone cant see thumbnails help me

**Comment by valoricDe** [comment]
It would be at least interesting how the benchmark was done. I just tested Aerys and had 5000 Request/s with throughput of 1.13MB on a Intel® Core™ i5-5300U CPU @ 2.30GHz × 4 with 8GB

```
./composer.phar require amphp/aerys
./vendor/amphp/aerys/bin/aerys
(in a separate terminal): wrk -t12 -c400 -d30s localhost:1337/router/myarg
```

**Comment by khelle** [comment]
Both React and Aerys are PHP async libraries not frameworks so comparing them to Kraken is irrelevant as they were created for different purposes. Additionaly, since v0.5 Kraken has been split into two projects to separate the framework and libraries code. This created the way to compare them so missing benchmarks are being created in the second one. You will be able to find them in each of libraries listed in https://github.com/dazzle-php/dazzle . At this moment only https://github.com/dazzle-php/event documentation is completed, but soon the rest will follow.
